name: Deploy static content to Pages

on:
  push:
    branches:
      - "master"

# Opcional: permite ejecutar manualmente desde la pestaña Actions
workflow_dispatch:

permissions:
  contents: read    # Permite leer el repo
  pages: write      # Permite desplegar a GH Pages
  id-token: write   # Permite la OIDC authentication

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Compila tu SCSS si lo requieres
      - name: Compile SCSS
        run: npm run sass

      # Construye el sitio (usa Eleventy para generar los archivos en ./docs)
      - name: Build Eleventy site
        run: npm run build

      # Sube la carpeta de salida (docs/) como artifact temporal
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs  # Ajusta si tu build es en otra carpeta

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      # 'url' se asigna internamente al terminar el deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
