name: Deploy static content to Pages

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read     # Permite leer el repo
  pages: write       # Permite desplegar a GH Pages
  id-token: write    # Permite la OIDC authentication

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # (Opcional) Compila tu SCSS
      - name: Compile SCSS
        run: npm run sass

      # Construye el sitio con Eleventy
      - name: Build Eleventy site
        run: npm run build

      # Sube la carpeta de salida (ej. "docs/") como artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs  # Ajusta si tu build sale en otra carpeta

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
